#############################################################################
# Makefile for building: qtgl2
# Generated by qmake (2.01a) (Qt 4.8.7) on: ? 9? 22 14:29:31 2017
# Project:  qtgl2.pro
# Template: app
# Command: /usr/lib64/qt4/bin/qmake -o Makefile qtgl2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Wall -pg -O0 `pkg-config --cflags --libs glib-2.0` -g -fopenmp -DDEBUG -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lGLU -lm -lboost_system -ltuplespace -lglib-2.0 -pg -g -fopenmp -luuid -lQtOpenGL -L/usr/lib64/qt4 -lQtGui -lQtNetwork -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib64/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = calc.cpp \
		dbgout.c \
		difint.cpp \
		dlst.c \
		fullscreenhint.cpp \
		glwidget.cpp \
		logutil.c \
		lupe.cpp \
		main.cpp \
		mainwindow.cpp \
		mandelbro.cpp \
		mylist.c \
		render.cpp \
		rendscroll.cpp \
		sp_server.c \
		task_spawner.cpp \
		tgroup.cpp \
		tile.cpp \
		version_window.cpp moc_fullscreenhint.cpp \
		moc_glwidget.cpp \
		moc_mainwindow.cpp \
		moc_rendscroll.cpp \
		moc_task_spawner.cpp \
		moc_version_window.cpp \
		qrc_resources.cpp
OBJECTS       = calc.o \
		dbgout.o \
		difint.o \
		dlst.o \
		fullscreenhint.o \
		glwidget.o \
		logutil.o \
		lupe.o \
		main.o \
		mainwindow.o \
		mandelbro.o \
		mylist.o \
		render.o \
		rendscroll.o \
		sp_server.o \
		task_spawner.o \
		tgroup.o \
		tile.o \
		version_window.o \
		moc_fullscreenhint.o \
		moc_glwidget.o \
		moc_mainwindow.o \
		moc_rendscroll.o \
		moc_task_spawner.o \
		moc_version_window.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtgl2.pro
QMAKE_TARGET  = qtgl2
DESTDIR       = 
TARGET        = qtgl2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_fullscreenhint.h ui_uimain.h ui_version.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtgl2.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtOpenGL.prl \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtNetwork.prl
	$(QMAKE) -o Makefile qtgl2.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtOpenGL.prl:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qtgl2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtgl21.0.0 || $(MKDIR) .tmp/qtgl21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtgl21.0.0/ && $(COPY_FILE) --parents calc.h dbgout.h dlst.h fullscreenhint.h glwidget.h logutil.h lupe.h mainwindow.h mandelbro.h mylist.h render.h rendscroll.h sp_server.h sslib.h task_spawner.h tile.h version.h version_window.h .tmp/qtgl21.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/qtgl21.0.0/ && $(COPY_FILE) --parents calc.cpp dbgout.c difint.cpp dlst.c fullscreenhint.cpp glwidget.cpp logutil.c lupe.cpp main.cpp mainwindow.cpp mandelbro.cpp mylist.c render.cpp rendscroll.cpp sp_server.c task_spawner.cpp tgroup.cpp tile.cpp version_window.cpp .tmp/qtgl21.0.0/ && $(COPY_FILE) --parents fullscreenhint.ui uimain.ui version.ui .tmp/qtgl21.0.0/ && (cd `dirname .tmp/qtgl21.0.0` && $(TAR) qtgl21.0.0.tar qtgl21.0.0 && $(COMPRESS) qtgl21.0.0.tar) && $(MOVE) `dirname .tmp/qtgl21.0.0`/qtgl21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtgl21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_fullscreenhint.cpp moc_glwidget.cpp moc_mainwindow.cpp moc_rendscroll.cpp moc_task_spawner.cpp moc_version_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_fullscreenhint.cpp moc_glwidget.cpp moc_mainwindow.cpp moc_rendscroll.cpp moc_task_spawner.cpp moc_version_window.cpp
moc_fullscreenhint.cpp: ui_fullscreenhint.h \
		fullscreenhint.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) fullscreenhint.h -o moc_fullscreenhint.cpp

moc_glwidget.cpp: render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		glwidget.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		glwidget.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) glwidget.h -o moc_glwidget.cpp

moc_mainwindow.cpp: render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		glwidget.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		mainwindow.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_rendscroll.cpp: mainwindow.h \
		render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		glwidget.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		rendscroll.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) rendscroll.h -o moc_rendscroll.cpp

moc_task_spawner.cpp: mandelbro.h \
		tile.h \
		render.h \
		lupe.h \
		glwidget.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		task_spawner.h \
		task_spawner.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) task_spawner.h -o moc_task_spawner.cpp

moc_version_window.cpp: version_window.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) version_window.h -o moc_version_window.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		resources/icon256.png
	/usr/lib64/qt4/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_fullscreenhint.h ui_uimain.h ui_version.h
compiler_uic_clean:
	-$(DEL_FILE) ui_fullscreenhint.h ui_uimain.h ui_version.h
ui_fullscreenhint.h: fullscreenhint.ui
	/usr/lib64/qt4/bin/uic fullscreenhint.ui -o ui_fullscreenhint.h

ui_uimain.h: uimain.ui \
		glwidget.h \
		rendscroll.h \
		render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		glwidget.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		mainwindow.h \
		render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		glwidget.h \
		ui_version.h \
		rendscroll.h \
		calc.h
	/usr/lib64/qt4/bin/uic uimain.ui -o ui_uimain.h

ui_version.h: version.ui
	/usr/lib64/qt4/bin/uic version.ui -o ui_version.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

calc.o: calc.cpp calc.h \
		sp_server.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calc.o calc.cpp

dbgout.o: dbgout.c dbgout.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o dbgout.o dbgout.c

difint.o: difint.cpp sslib.h \
		render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		glwidget.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o difint.o difint.cpp

dlst.o: dlst.c dlst.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o dlst.o dlst.c

fullscreenhint.o: fullscreenhint.cpp fullscreenhint.h \
		ui_fullscreenhint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fullscreenhint.o fullscreenhint.cpp

glwidget.o: glwidget.cpp glwidget.h \
		render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

logutil.o: logutil.c logutil.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o logutil.o logutil.c

lupe.o: lupe.cpp lupe.h \
		render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		glwidget.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		dbgout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lupe.o lupe.cpp

main.o: main.cpp mainwindow.h \
		render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		glwidget.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		sp_server.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		glwidget.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		ui_uimain.h \
		version_window.h \
		ui_fullscreenhint.h \
		fullscreenhint.h \
		version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mandelbro.o: mandelbro.cpp mandelbro.h \
		tile.h \
		render.h \
		lupe.h \
		glwidget.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		task_spawner.h \
		dbgout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mandelbro.o mandelbro.cpp

mylist.o: mylist.c mylist.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mylist.o mylist.c

render.o: render.cpp render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		glwidget.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		sslib.h \
		dbgout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o render.o render.cpp

rendscroll.o: rendscroll.cpp rendscroll.h \
		mainwindow.h \
		render.h \
		tile.h \
		mandelbro.h \
		task_spawner.h \
		lupe.h \
		glwidget.h \
		ui_version.h \
		calc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rendscroll.o rendscroll.cpp

sp_server.o: sp_server.c logutil.h \
		mylist.h \
		dbgout.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sp_server.o sp_server.c

task_spawner.o: task_spawner.cpp task_spawner.h \
		mandelbro.h \
		tile.h \
		render.h \
		lupe.h \
		glwidget.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o task_spawner.o task_spawner.cpp

tgroup.o: tgroup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tgroup.o tgroup.cpp

tile.o: tile.cpp tile.h \
		render.h \
		lupe.h \
		glwidget.h \
		mainwindow.h \
		ui_version.h \
		rendscroll.h \
		calc.h \
		mandelbro.h \
		task_spawner.h \
		dbgout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tile.o tile.cpp

version_window.o: version_window.cpp version_window.h \
		version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o version_window.o version_window.cpp

moc_fullscreenhint.o: moc_fullscreenhint.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fullscreenhint.o moc_fullscreenhint.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_rendscroll.o: moc_rendscroll.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rendscroll.o moc_rendscroll.cpp

moc_task_spawner.o: moc_task_spawner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_task_spawner.o moc_task_spawner.cpp

moc_version_window.o: moc_version_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_version_window.o moc_version_window.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

